# Generated by Django 5.0 on 2025-09-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remote_onsite',
            field=models.CharField(choices=[('R', 'Remote'), ('O', 'Onsite')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='job',
            name='visa_sponsorship',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
