# Generated by Django 5.0 on 2025-10-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_show_email_profile_show_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_resume',
        ),
        migrations.AddField(
            model_name='profile',
            name='show_education',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_experience',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_headline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_skills',
            field=models.BooleanField(default=True),
        ),
    ]
